Traceback (most recent call last):
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class ClassName(object):
    """This is a class"""
    class_variable
    def __init__(self,*args):
        self.args=args
        
    def _repr_(self):
        return "Something to represent the object as a string"
    
    def other_method(self, *args):
        return "do something else"
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-76f503b60657>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mclass[0m [0mClassName[0m[1;33m([0m[0mobject[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m     [1;34m"""This is a class"""[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m     [0mclass_variable[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [1;32mdef[0m [0m__init__[0m[1;33m([0m[0mself[0m[1;33m,[0m[1;33m*[0m[0margs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m         [0mself[0m[1;33m.[0m[0margs[0m[1;33m=[0m[0margs[0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-1-76f503b60657>[0m in [0;36mClassName[1;34m()[0m
[0;32m      1[0m [1;32mclass[0m [0mClassName[0m[1;33m([0m[0mobject[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m     [1;34m"""This is a class"""[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m     [0mclass_variable[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m     [1;32mdef[0m [0m__init__[0m[1;33m([0m[0mself[0m[1;33m,[0m[1;33m*[0m[0margs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m         [0mself[0m[1;33m.[0m[0margs[0m[1;33m=[0m[0margs[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'class_variable' is not defined
NameError: name 'class_variable' is not defined

